[package]
name = "onchain_evm"
version = "0.2.0"
edition = "2021"

[lib]
name = "onchain_evm"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.38"
revm = { version = "41", features = ["std"] }
revm-database = { version = "41", features = ["alloydb"] }
alloy-eips = "2.1"
alloy-primitives = "1.6"
alloy-provider = { version = "2.1", features = ["reqwest"] }
alloy-rpc-client = "2.1"
alloy-transport-http = "2.1"
reqwest = "0.13"
tokio = { version = "1", features = ["rt"] }
serde_json = "1"
hex = "0.4"
